<a href="https://colab.research.google.com/github/9terry-student/PyTorch/blob/main/Tensor_Manipulation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [ ]:
import numpy as np
import torch

# NumPy Review

In [ ]:
# 1D Array with NumPy
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ',t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1]) # Element
print('t[2:5] t[4:-1] = ',t[2:5],t[4:-1]) # Slicing
print('t[:2] t[3:] = ',t[:2],t[3:]) # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
# 2D Array with NumPy
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,7.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  7.]
 [10. 11. 12.]]


In [ ]:
print('Rank of t: ',t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# PyTorch Tensor

In [ ]:
# 1D Array with PyTorch
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0],t[1],t[-1]) # Element
print(t[2:5],t[4:-1]) # Slicing
print(t[:2],t[3:]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2D Array with PyTorch
t=torch.FloatTensor([[1.,2.,3.],
                     [4.,5.,6.],
                     [7.,8.,9.],
                     [10.,11.,12.]
                     ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Broadcasting

In [ ]:
# Same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3]) # 3->[[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


# Multiplication vs Matrix Multiplication

In [ ]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape) # 2 x 2
print('Shape of Matrix 2: ',m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape) # 2 x 2
print('Shape of Matrix 2: ',m2.shape) # 2 x 1
print(m1*m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [ ]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [ ]:
# Can't use mean() on integers
t= torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


In [ ]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ',t.max(dim=0)[0])
print('Argmax: ',t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
